### ISSUE TITLE
Create an Octave 4.4.1 App-Bundle

### ISSUE THREAD

**Issue by schoeps** [octave-app/octave-app-bundler#39]
Shall we move on?

http://octave.1599824.n4.nabble.com/First-Octave-4-4-1-release-candidate-available-for-ftp-td4688671.html

**Comment by apjanke** [comment]
Let's try to get a release of 4.4.0 out the door first, and then do the upgrade to 4.4.1 as a next step. That will give us practice with Octave upgrade process. As far as I can tell, 4.4.1 doesn't contain any fixes directly relevant to Octave.app, so it's not urgent to pull it in.

**Comment by apjanke** [comment]
Octave 4.4.1 golden master is out: http://lists.gnu.org/archive/html/octave-maintainers/2018-08/msg00066.html. I'll start making a 4.4.1 build now. (While still pushing our 4.4.0 out to release.)

**Comment by apjanke** [comment]
Oh, darnit. There's a snag: #47

**Comment by apjanke** [comment]
4.4.1 beta4 is out: https://github.com/octave-app/octave-app/releases/tag/v4.4.1-beta4

I think this one is ready to be a Release Candidate.

**Comment by apjanke** [comment]
Hi Sebastian. I've made a beta5 build. Could you test this one? There's a significant change: I reverted from our hacked `qt-octave-app` Qt to vanilla Qt, to see if it clears up some crashes and hangs I've been having lately, primarily related to saving files while stopped in them in the debugger.

Could you give this a test drive for a bit and tell me if:
1. It seems crashy?
2. You see [this "Failed assertion warning: (FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'" warning](https://github.com/octave-app/octave-app-bundler/issues/13)?

**Comment by apjanke** [comment]
TODO note for me: Will need to do at least one more beta build with an updated JDK installation, because there are new updates out for both JDK 8 and JDK 11, and [dynamic JVM detection](https://savannah.gnu.org/bugs/index.php?54219) is not implemented in Octave yet.

**Comment by schoeps** [comment]
@apjanke Sure, I will download beta5 right away. Typically, I am not using the GUI debugger much but I surely can play with it to provoke the errors mentioned!

**Comment by apjanke** [comment]
I'm all the way up to beta 8 now, actually: https://github.com/octave-app/octave-app/releases/tag/v4.4.1-beta8

**Comment by schoeps** [comment]
Yes, I realized :)

**Comment by schoeps** [comment]
The rc1 (and the other recent versions that I tried) works fine for me. I did not see issues with the debugger but running `__run_test_suite__` gives 4 fails in 
- `image/getframe.m`
- `plot/appearance/legend.m`
- `plot/util/copyobj.m `
- `plot/util/hgsave.m`

and several warning on `set term qt`. We still have the problem that some files (`dir.m`, `set.m`, `quantile.m`, `ls.m`) are opened while running the test suite. As far as I recall, there is a bug report about it, right? This is all not that serious, I guess.

**Comment by apjanke** [comment]
The `getframe` and `legend` might be new; I don't recall seeing those when I ran the tests in this or previous releases. And I reran `__run_test_suite__` just now in 4.4.1 RC1 on my macOS 10.13.6 iMac, and they passed without errors.

The `copyobj` and `hgsave` are old, as well as the `set term qt` warnings.

Yep, the "files opened during test suite" has been reported upstream: https://github.com/octave-app/octave-app-bundler/issues/21 and https://savannah.gnu.org/bugs/?49119. I believe that's fixed in the forthcoming Octave 5.0 release.

I don't consider these blockers, do you? I'd prefer to roll on and get this in the hands of users instead of working out every last kink, and move our focus to the 5.x release. Since upstream doesn't go back and do patch releases for older minor versions, these will likely need to wait until 5.x or 6.x for fixes anyway.

My big issue is that Octave has been hanging a lot for me. But I don't think there's much we can do about that in the short term – I doubt it's specific to the Octave.app packaging, and it'll need serious work upstream. So I don't think that should block the release.

Also, running the test suite and comparing results should get easier if https://savannah.gnu.org/bugs/index.php?55522 makes it in, so there's a failure summary at the end of the output.

**Comment by schoeps** [comment]
Yes, let's proceed. Most users will not run the test suite and the remaining bugs are rather "cosmetical".

**Comment by apjanke** [comment]
Argh, those "set term qt" warnings were actually a regression of https://github.com/octave-app/octave-app-bundler/issues/18 due to linking against the non-hacked Qt now. That's non-cosmetic and needs to be fixed. RC2 forthcoming.

**Comment by schoeps** [comment]
Do you know what to do? Do you need help debugging?

**Comment by apjanke** [comment]
I know what to do. I have already fixed it by modifying out `gnuplot` formulae to build with Qt by default. I just need to get the RC2 built.

**Comment by apjanke** [comment]
4.4.1 RC2 is out: https://github.com/octave-app/octave-app/releases/tag/v4.4.1-RC2

**Comment by schoeps** [comment]
Indeed the error `set term qt` disappeared. A also checked that plotting works with `gnuplot` (qt backend). I still see fails in two test: `plot/util/copyobj.m` and `plot/util/hgsave.m` but this is not too scary.

**Comment by apjanke** [comment]
No new bugs reported. I'm ready to make this RC2 the official release, if you have no objections.

**Comment by schoeps** [comment]
Sure! Let's do that quickly before Octave 5.x becomes official :)

**Comment by apjanke** [comment]
Okay. I've pushed the [4.4.1 release](https://github.com/octave-app/octave-app/releases/tag/v4.4.1) and update the [octave-app.org web page](https://octave-app.org).

Closing this as done.

**Comment by apjanke** [comment]
And it's 5.1.0 time: https://github.com/octave-app/octave-app-bundler/issues/71. I might be able to get a beta out tomorrow.
